templars_krak/Flask 02 BP users/users/models.py
from uuid import uuid4
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

from app import db
from app import login


# intermediate table
user_role = db.Table('user_roles',
    db.Column('user_id', db.String(36), db.ForeignKey('user.id')),
    db.Column('role_id', db.String(36), db.ForeignKey('role.id')),
    db.UniqueConstraint('user_id', 'role_id', name="unique_constraint"),
)

class Role(db.Model):
    """Roles are used for permissions"""
    id = db.Column(db.String(36), primary_key=True, default=str(uuid4()))
    name = db.Column(db.String(64), nullable=False, unique=True, index=True)

    def __repr__(self) -> str:
        return f"<Role: {self.name}>"

    @classmethod
    def get_name(cls, name):
        role = Role.query.filter_by(name=name).first()
        if role is None:
            raise Exception(f"Role '{name}' does not exists.")
        return role


class User(UserMixin, db.Model):
    id = db.Column(db.String(36), primary_key=True, default=str(uuid4()))
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    date_created = db.Column(db.DateTime, default=datetime.utcnow())
    last_seen = db.Column(db.DateTime, default=datetime.utcnow())


    roles = db.relationship(
        'Role', secondary=user_role,
        backref=db.backref('users', lazy='dynamic'), lazy='dynamic'
    )

    def __repr__(self):
        return f"<User: {self.username}>"

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def add_role(self, role: str):
        if self.has_role(role):
            return
        role = Role.get_name(role)
        self.roles.append(role)

    def remove_role(self, role: str):
        role = Role.get_name(role)
        self.roles.remove(role)

    def has_role(self, role: str):
        role = Role.get_name(role)
        if role in self.roles.all():
            return True
        else:
            return False



@login.user_loader
def load_user(id):
    return User.query.get(str(id))

templars_krak/Flask 02 BP users/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, EqualTo, ValidationError

from app.users.models import User

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember_me = BooleanField("remember me")
    submit = SubmitField("Login")


class SignInForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField("Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    password2 = PasswordField(
        "Repeat password", validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField("Register")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Username already used by someone.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError("Email already used by someone")

templars_krak/Flask 02 BP users/users/__init__.py
from flask import Blueprint


users = Blueprint(
    "users",
    __name__,
    static_folder="static",
    template_folder="templates"
)

from . import views

templars_krak/Flask 02 BP users/users/views.py
from datetime import datetime

from flask import request, render_template, redirect, flash, url_for
from werkzeug.urls import url_parse

from app import db
from .forms import LoginForm, SignInForm
from app import app
from flask_login import current_user, login_user, logout_user
from .models import User

from . import users


@users.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('users.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('index')
        return redirect(next_page)

    context = {
        "form": form,
    }
    return render_template("users/login.html", **context)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))


@users.route("/sign_in", methods=['GET', 'POST'])
def sign_in():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = SignInForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data
            )
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Registration successfully done.")
        return redirect(url_for('users.login'))
    return render_template("users/sign_in.html", title="Sign in", form=form)

templars_krak/Flask 02 BP users/users/templates/users/login.html
{% extends "_base.html" %}


{% block content %}
<h1>login</h1>

<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.username.label }} <br>
        {{ form.username(size=32) }} <br>
        {% for error in form.username.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password.label }} <br>
        {{ form.password(size=32) }} <br>
        {% for error in form.password.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </p>
    <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
    <p>{{ form.submit(class="btn btn-success") }}</p>
</form>

    <p>New user ? please <a href="{{ url_for('users.sign_in') }}">Sign in.</a></p>

{% endblock content %}

templars_krak/Flask 02 BP users/users/templates/users/sign_in.html
{% extends "_base.html" %}

{% block content %}

<h1>Sign in</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}

    <p>
        {{ form.username.label }} <br>
        {{ form.username(size=32) }} <br>
        {% for error in form.username.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.email.label }} <br>
        {{ form.email(size=32) }} <br>
        {% for error in form.email.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password.label }} <br>
        {{ form.password(size=32) }} <br>
        {% for error in form.password.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password2.label }} <br>
        {{ form.password2(size=32) }} <br>
        {% for error in form.password2.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.submit }}
    </p>

</form>



{% endblock content %}